### ISSUE TITLE
ctrl+n, ctrl+p are not working for Suggest Widget.

### ISSUE THREAD

**Issue by unakatsuo** [nana4gonta/emacs-visual-studio-code#6]
I found the lines where manage these key bindings. But they seem to be ignored.

https://github.com/nana4gonta/emacs-visual-studio-code/blob/master/release/keybindings-windows.json#L46-L50

https://github.com/nana4gonta/emacs-visual-studio-code/blob/master/release/keybindings-windows.json#L57-L60

I suspect that the `keybindings.json` is evaluated from the bottom so that the some rules are ignored. Currently, the behavior seems that ctrl+p, ctrl+n for "cursorUp", "cursorDown" always capture keys because these rules appear in later lines.

https://github.com/nana4gonta/emacs-visual-studio-code/blob/master/release/keybindings-windows.json#L91-L100 

The problem was fixed when I moved the L46-L50 and L57-L60 to the line after L100.

**Comment by nana4gonta** [comment]
Thanks @unakatsuo .
I think it will probably work if put `cursors.json` at the beginning, when run the build script.

I'll try checking behavior.
Please wait a little longer.

**Comment by nana4gonta** [comment]
fixed in b7e02cacbbbea0fb1009b782984812e981b7fae0 and 653872e8e09d54ff6f8a457d261544baff2c736b
Thanks your issue.
