### ISSUE TITLE
openFile to openFileFolder

### ISSUE THREAD

**Issue by gih2yun** [nana4gonta/emacs-visual-studio-code#8]
Thanks.

I tried to this emacs binding. But openFile is not working with new version of visual code.

I've changed it to `openFileFolder`, then it works.

Thanks.

**Comment by nana4gonta** [comment]
Thanks, @gih2yun.
I'm sorry to replay late.

Do you use OSX ?
It is the OSX-specific command.

**Comment by gih2yun** [comment]
Yes, I am.
Thanks.

2016년 4월 12일 (화) 오전 1:51, KzKarino notifications@github.com님이 작성:
